# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://skink.app
title: Skink
email: ask@skink.app
author: Rorki & Norefle
description: > # "Write an awesome description for your new site here.
  Landing page for an amazing Skink application.
copyright: "Copyright &copy; 2020 Skink App. All Rights Reserved."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  #  - title: twitter
  #    url: https://skink.app
  #  - title: github
  #    url: https://skink.app
  - title: linkedin
    url: https://www.linkedin.com/company/skink-app/about
